### ISSUE TITLE
为什么请求回来的action.payload中没有data参数？

### ISSUE THREAD

**Issue by saga7878** [jasonslyvia/redux-composable-fetch#7]
![1521110225 1](https://user-images.githubusercontent.com/21330858/37458405-ebc4c4bc-287f-11e8-8cb5-e1aa7073dc94.jpg)
下面是我的代码：
![d 34gt yq_mdhlt j3c](https://user-images.githubusercontent.com/21330858/37458452-10322420-2880-11e8-93e9-afa346927f03.png)

**Comment by saga7878** [comment]
我要如何获取请求回来的数据？这个对我非常重要，希望您能解答一下

**Comment by jasonslyvia** [comment]
你是如何配置 fetch middleware 的？一般在实际业务中使用的时候，还需要针对 fetch middleware 配置一些后置处理程序，这样 reducer 中拿到的会是真实数据而不是 fetch 返回的 ReadableStream。

**Comment by jasonslyvia** [comment]
```js
const middlewares = [
  createFetchMiddleware({
    afterFetch({ action, result }) {
      // 这里 return 的数据就是 reducer 中的 action.payload，result 是 fetch 返回的 ReadableStream
      return result.json();
    }
  })
];

const enhancer = composeEnhancers(applyMiddleware(...middlewares));
const store = createStore(reducers, initialState, enhancer);
```

**Comment by saga7878** [comment]
非常感谢，是我的问题，我没有配置好 fetch middleware，可以关闭这个问题了，redux-composable-fetch解决了我很多问题，非常感谢！！！

**Comment by jasonslyvia** [comment]
:)
